- name: Forks and Serial Rollout Demo
  hosts: all
  gather_facts: false
  max_fail_percentage: 35
  #serial: 7
  serial:
    - 10%
    - 30%
    - 50%
    - 100%
  vars:
    host_fail:
      - servera.lab.example.com
      - db_server2
  tasks:
    - name: is database OK
      ansible.builtin.command: sleep 2
      run_once: true
      
    - name: Take down device from LB
      ansible.builtin.command: sleep 2

    - name: Update OS
      ansible.builtin.command: sleep 2
      failed_when: inventory_hostname in host_fail
      
    - name: Update other Config
      ansible.builtin.command: sleep 2

    - name: Put device back to LB
      ansible.builtin.command: sleep 2
