- name: Install Httpd web server
  hosts: servera*
  gather_facts: true
  become: true
  tasks:
    - name: Install httpd Server first
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Deply a simple html app
      ansible.builtin.copy:
        content: "This is First Page"
        dest: /var/www/html/index.html
        mode: 0644

    - name: Start web service
      ansible.builtin.service:
        name: httpd
        state: started
