---
# tasks file for security_server

- name: Install firewalld packages
  ansible.builtin.dnf:
    name: "{{ security_server_package }}"
    state: present
  notify:
    - security package installed

- name: Open Firewall Port
  ansible.posix.firewalld:
    service: "{{ security_server_service }}"
    permanent: true
    state: enabled
    immediate: true
  notify:
    - security port opened
